language: node_js
# nodejs版本
node_js: stable
 

 
 
# S: Build Lifecycle
install:
  - npm install
 
before_script:
 

script:
  - hexo clean
  - hexo g
 
after_script:
  - cd public
  - git init
  - git config user.name "${GIT_NAME}"
  - git config user.email "${GIT_EMAIL}"
  - git add .
  - git commit -m "Update tools"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${gh_ref}" master:master
# E: Build LifeCycle

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - hexo
env:
  global:
  - gh_ref: github.com/GY00156/gy00156.github.io.git